apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: default
spec:
  type: NodePort
  ports:
  - name: "webapp-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: webapp
  
