apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - webapp-deployment.yaml
images:
  - name: dominicpg/sampleapp
    newName: dominicpg/sampleapp
    newTag: main-92cf479d-1636223465 # {"$imagepolicy": "flux-system:sampleapp:tag"}
