apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - webapp-deployment.yaml
images:
  - name: dominicpg/sampleapp
    newTag: main-260a2a8d-1635791705 # {"$imagepolicy": "flux-system:sampleapp:tag"}
