apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - webapp-deployment.yaml
images:
  - name: dominicpg/sampleapp
    newName: dominicpg/sampleapp
    newTag: main-f2592afe-1635868147 # {"$imagepolicy": "flux-system:sampleapp:tag"}
