apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- webapp-deployment.yaml

images:
- name: dominicpg/sampleapp
  newTag: v2 # {"$imagepolicy": "flux-system:sampleapp:tag"}
