apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 2
  template:
    spec:
      $setElementOrder/containers:
      - name: webapp
      containers:
      - image: dominicpg/sampleapp:v2
        name: webapp
