apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: dominicpg/sampleapp # {"$imagepolicy": "flux-system:podinfo"}
        name: webapp
        ports:
        - containerPort: 80
          name: webapp
